docs_list_title: hosts
docs:

- name: Jessica MacLeod
  bio: Jessica MacLeod is a Principal at <a href="http://carstenadvisory.com">Carsten Advisory</a>, a consultancy focused on helping government and the businesses that support it thrive in the digital age.
  img: jessica-carsten.jpg
  twitter: https://twitter.com/JessicaCarsten
  linkedin: https://www.linkedin.com/in/jessicacarsten/

- name: Luke Fretwell
  bio: <a href="https://lukefretwell.com">Luke Fretwell</a> is the CEO of <a href="https://proudcity.com">ProudCity</a> and writes about civic innovation and technology at <a href="https://govfresh.com">GovFresh</a>.
  img: luke-fretwell.jpg
  twitter: https://twitter.com/lukefretwell
  linkedin: https://www.linkedin.com/in/lukefretwell
